on:
  push:
    branches:
      - "**" # TODO | That would be master
name: build-test-deploy
jobs:
  job:
    runs-on: ubuntu-22.04
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: "${{ secrets.AWS_KEY }}"
          name: key_pair_1.pem
          config: "${{ secrets.SSH_CONFIG }}"
      - id: publish
        run: yarn cidi:local
